#!/usr/bin/env bash

# archive, verbose, don't sync deploy script, use ssh remote shell
rsync -av --safe-links --exclude 'deploy' --exclude '.git*' -e ssh ./ ganbaru.games:/var/www/ganbaru.games/html/
